[
  {
    tags: [
      "capacidad académica",
      "compromiso académico",
      "conciencia de roles",
      "habilidades socioemocionales",
      "recursos educativos",
    ],
    answers: [
      "El cuidador considera que acompaña más al estudiante",
      "El cuidador considera que actividades de autosuperación para el cuidador permitiria acompañar académicamente al estudiante",
      "El cuidador considera que conocer el estilo de aprendizaje del estudiante es una acción efectiva para el aprendizaje",
      "El cuidador considera que el acompañamiento académico permite que el estudiante aprenda más y mejor",
      "El cuidador considera que el cruce de horarios por el trabajo, la falta o el orden en el tiempo dificultó su acompañamiento",
      "El cuidador considera que el internet permitirá involucrarse activamente en la educación del estudiante",
      "El cuidador considera que está más motivado para acompañar academicamente al estudiante",
      "El cuidador considera que explicarle y permitir que el estudiante resuelva las tareas por sí mismo es una acción efectiva para apoyar el aprendizaje",
      "El cuidador considera que hay más seguridad en el estudiante",
      "El cuidador considera que la falta de internet dificulta la participación en proyectos de intervención",
      "El cuidador considera que la interacción con  los demás cuidadores genera sensaciones positivas",
      "El cuidador considera que la interacción con los demás cuidadores genera aprendizaje colaborativo",
      "El cuidador considera que la intervención permite que el estudiante tenga mejores calificaciones",
      "El cuidador considera que las rutinas de estudio les permiten tener claros los horarios y responsabilidades académicas a desarrollar",
      "El cuidador considera que su falta de formación académica le ha impedido involucrarse más en la educación del estudiante",
      "El cuidador cree que los audios y los videos informativos fortalecerían las rutinas de estudios",
      "El cuidador cree que los juegos y nuevas dinámicas les permitirían el acompañamiento académico que realiza con el estudiante",
      "El cuidador cree que un compartir permitiría el acompañamiento académico que realiza con el estudiante",
      "El cuidador espera que el acompañamiento académico le permita al estudiante mejorar académicamente",
      "El cuidador espera que el acompañamiento académico le permita al estudiante salir adelante",
      "El cuidador se percibe con un rol de facilitador de conocimiento",
    ],
    tagged: {
      "conciencia de roles": [
        "El cuidador considera que actividades de autosuperación para el cuidador permitiria acompañar académicamente al estudiante",
        "El cuidador considera que el acompañamiento académico permite que el estudiante aprenda más y mejor",
        "El cuidador considera que el acompañamiento académico permite que el estudiante aprenda más y mejor",
        "El cuidador considera que explicarle y permitir que el estudiante resuelva las tareas por sí mismo es una acción efectiva para apoyar el aprendizaje",
        "El cuidador considera que la interacción con los demás cuidadores genera aprendizaje colaborativo",
        "El cuidador se percibe con un rol de facilitador de conocimiento",
      ],
      "capacidad académica": [
        "El cuidador considera que la intervención permite que el estudiante tenga mejores calificaciones",
        "El cuidador considera que su falta de formación académica le ha impedido involucrarse más en la educación del estudiante",
        "El cuidador espera que el acompañamiento académico le permita al estudiante mejorar académicamente",
        "El cuidador espera que el acompañamiento académico le permita al estudiante mejorar académicamente",
        "El cuidador espera que el acompañamiento académico le permita al estudiante salir adelante",
      ],
      "habilidades socioemocionales": [
        "El cuidador considera que está más motivado para acompañar academicamente al estudiante",
        "El cuidador considera que hay más seguridad en el estudiante",
        "El cuidador considera que la interacción con  los demás cuidadores genera sensaciones positivas",
      ],
      "compromiso académico": [
        "El cuidador considera que acompaña más al estudiante",
        "El cuidador considera que conocer el estilo de aprendizaje del estudiante es una acción efectiva para el aprendizaje",
        "El cuidador considera que el cruce de horarios por el trabajo, la falta o el orden en el tiempo dificultó su acompañamiento",
        "El cuidador considera que las rutinas de estudio les permiten tener claros los horarios y responsabilidades académicas a desarrollar",
      ],
      "recursos educativos": [
        "El cuidador considera que el internet permitirá involucrarse activamente en la educación del estudiante",
        "El cuidador considera que el internet permitirá involucrarse activamente en la educación del estudiante",
        "El cuidador considera que la falta de internet dificulta la participación en proyectos de intervención",
        "El cuidador cree que los audios y los videos informativos fortalecerían las rutinas de estudios",
        "El cuidador cree que los juegos y nuevas dinámicas les permitirían el acompañamiento académico que realiza con el estudiante",
        "El cuidador cree que un compartir permitiría el acompañamiento académico que realiza con el estudiante",
      ],
    },
    name: "cuidador_1",
    id: 1,
    totalTags: 5,
    totalAnswers: 21,
  },
  {
    tags: [
      "capacidad académica",
      "compromiso académico",
      "conciencia de roles",
      "habilidades socioemocionales",
      "recursos educativos",
    ],
    answers: [
      "El cuidador considera el estudiante tendrá más deseo, motivación o interés de estudiar gracias al proyecto de intervención",
      "El cuidador considera necesario un informe rutinario sobre la actualidad académica del estudiante",
      "El cuidador considera que al estudiante ya no le da pena hacer preguntas a la docente",
      "El cuidador considera que el acompañamiento académico permite que el estudiante aprenda más y mejor",
      "El cuidador considera que el acompañamiento académico permite que el estudiante se sienta acompañado",
      "El cuidador considera que el cruce de horarios por el trabajo, la falta o el orden en el tiempo dificultó su acompañamiento",
      "El cuidador considera que el estudiante está más despierto académicamente",
      "El cuidador considera que el estudiante le va a solicitar más acompañamiento académico",
      "El cuidador considera que el internet permitirá involucrarse activamente en la educación del estudiante",
      "El cuidador considera que está más pendiente de la educación del estudiante",
      "El cuidador considera que está más pendiente de las tareas del estudiante",
      "El cuidador considera que está más pendiente de lo que no entiende el estudiante",
      "El cuidador considera que la falta de costumbre en el estudiante ha impedido el establecimiento de rutinas de estudio",
      "El cuidador considera que la falta de entendimiento por parte del estudiante le ha impedido involucrarse más en la educación del estudiante",
      "El cuidador considera que la interacción con  los demás cuidadores genera sensaciones positivas",
      "El cuidador considera que la interacción con los demás cuidadores genera aprendizaje colaborativo",
      "El cuidador considera que las rutinas de estudio desarrollan responsabilidad en el estudiante",
      "El cuidador considera que las rutinas de estudio permitirán que el estudiante aprenderá más fácilmente",
      "El cuidador considera que leer y explicar al estudiante lo que debe aprender es una acción efectiva para el aprendizaje",
      "El cuidador considera que repetir temas ya estudiados junto con el estudiante le ha impedido involucrarse más en la educación del estudiante",
      "El cuidador considera que se generó un clima de confianza entre el cuidador y el estudiante",
      "El cuidador cree que los audios y los videos informativos fortalecerían las rutinas de estudios",
      "El cuidador cree que los juegos y nuevas dinámicas les permitirían el acompañamiento académico que realiza con el estudiante",
      "El cuidador espera estar más pendiente del acompañamiento académico en el estudiante",
      "El cuidador espera que el acompañamiento académico le permita al estudiante mejorar académicamente",
      "El cuidador se percibe con un rol de acompañamiento académico constante y consciente",
    ],
    tagged: {
      "habilidades socioemocionales": [
        "El cuidador considera que al estudiante ya no le da pena hacer preguntas a la docente",
        "El cuidador considera que el acompañamiento académico permite que el estudiante se sienta acompañado",
        "El cuidador considera que la interacción con  los demás cuidadores genera sensaciones positivas",
        "El cuidador considera que se generó un clima de confianza entre el cuidador y el estudiante",
      ],
      "conciencia de roles": [
        "El cuidador considera que el acompañamiento académico permite que el estudiante aprenda más y mejor",
        "El cuidador considera que el estudiante le va a solicitar más acompañamiento académico",
        "El cuidador considera que la interacción con los demás cuidadores genera aprendizaje colaborativo",
        "El cuidador considera que leer y explicar al estudiante lo que debe aprender es una acción efectiva para el aprendizaje",
        "El cuidador se percibe con un rol de acompañamiento académico constante y consciente",
      ],
      "compromiso académico": [
        "El cuidador considera el estudiante tendrá más deseo, motivación o interés de estudiar gracias al proyecto de intervención",
        "El cuidador considera que el cruce de horarios por el trabajo, la falta o el orden en el tiempo dificultó su acompañamiento",
        "El cuidador considera que el estudiante está más despierto académicamente",
        "El cuidador considera que está más pendiente de la educación del estudiante",
        "El cuidador considera que está más pendiente de las tareas del estudiante",
        "El cuidador considera que está más pendiente de lo que no entiende el estudiante",
        "El cuidador considera que la falta de costumbre en el estudiante ha impedido el establecimiento de rutinas de estudio",
        "El cuidador considera que las rutinas de estudio desarrollan responsabilidad en el estudiante",
        "El cuidador considera que las rutinas de estudio permitirán que el estudiante aprenderá más fácilmente",
        "El cuidador espera estar más pendiente del acompañamiento académico en el estudiante",
      ],
      "capacidad académica": [
        "El cuidador considera que la falta de entendimiento por parte del estudiante le ha impedido involucrarse más en la educación del estudiante",
        "El cuidador considera que repetir temas ya estudiados junto con el estudiante le ha impedido involucrarse más en la educación del estudiante",
        "El cuidador espera que el acompañamiento académico le permita al estudiante mejorar académicamente",
      ],
      "recursos educativos": [
        "El cuidador considera necesario un informe rutinario sobre la actualidad académica del estudiante",
        "El cuidador considera que el internet permitirá involucrarse activamente en la educación del estudiante",
        "El cuidador cree que los audios y los videos informativos fortalecerían las rutinas de estudios",
        "El cuidador cree que los juegos y nuevas dinámicas les permitirían el acompañamiento académico que realiza con el estudiante",
      ],
    },
    name: "cuidador_2",
    id: 2,
    totalTags: 5,
    totalAnswers: 26,
  },
  {
    tags: [
      "capacidad académica",
      "compromiso académico",
      "conciencia de roles",
      "habilidades socioemocionales",
      "recursos educativos",
    ],
    answers: [
      "El cuidador considera necesario un informe rutinario sobre la actualidad académica del estudiante",
      "El cuidador considera que acompaña más al estudiante",
      "El cuidador considera que actividades de autosuperación para el cuidador permitiria acompañar académicamente al estudiante",
      "El cuidador considera que el cruce de horarios por el trabajo, la falta o el orden en el tiempo dificultó su acompañamiento",
      "El cuidador considera que el estudiante va a sentirse seguro y respaldado al saber que tiene apoyo",
      "El cuidador considera que el internet permitirá involucrarse activamente en la educación del estudiante",
      "El cuidador considera que estaba dormido frente a las necesidades académicas del estudiante",
      "El cuidador considera que estar presente para resolver las dudas que el estudiante tenga es una acción efectiva para el aprendizaje",
      "El cuidador considera que la falta de costumbre en el estudiante ha impedido el establecimiento de rutinas de estudio",
      "El cuidador considera que la interacción con  los demás cuidadores genera sensaciones positivas",
      "El cuidador considera que la interacción con los demás cuidadores genera aprendizaje colaborativo",
      "El cuidador considera que la percepción del estudiante hacia él como actora ajena al conocimiento ha impedido establecer de rutinas de estudio",
      "El cuidador considera que las rutinas de estudio les permiten tener claros los horarios y responsabilidades académicas a desarrollar",
      "El cuidador considera que los libros le permitirán involucrarse activamente en la educación del estudiante",
      "El cuidador considera que su rol le permite al estudiante sentirse apoyados y con confianza",
      "El cuidador cree que los juegos y nuevas dinámicas les permitirían el acompañamiento académico que realiza con el estudiante",
      "El cuidador espera que el acompañamiento académico desarrolle la pérdida del miedo en el estudiante",
      "El cuidador espera que el acompañamiento académico genere sensación de apoyo en el estudiante",
      "El cuidador espera que el acompañamiento académico le permita al estudiante mejorar académicamente",
      "El cuidador espera que el acompañamiento académico potencie la interacción social por parte del estudiante",
      "El cuidador reconoce la importancia del acompañamiento académico",
    ],
    tagged: {
      "capacidad académica": [
        "El cuidador espera que el acompañamiento académico le permita al estudiante mejorar académicamente",
      ],
      "compromiso académico": [
        "El cuidador considera que acompaña más al estudiante",
        "El cuidador considera que actividades de autosuperación para el cuidador permitiria acompañar académicamente al estudiante",
        "El cuidador considera que el cruce de horarios por el trabajo, la falta o el orden en el tiempo dificultó su acompañamiento",
        "El cuidador considera que el cruce de horarios por el trabajo, la falta o el orden en el tiempo dificultó su acompañamiento",
        "El cuidador considera que la falta de costumbre en el estudiante ha impedido el establecimiento de rutinas de estudio",
        "El cuidador considera que las rutinas de estudio les permiten tener claros los horarios y responsabilidades académicas a desarrollar",
      ],
      "conciencia de roles": [
        "El cuidador considera que estaba dormido frente a las necesidades académicas del estudiante",
        "El cuidador considera que estar presente para resolver las dudas que el estudiante tenga es una acción efectiva para el aprendizaje",
        "El cuidador considera que la interacción con los demás cuidadores genera aprendizaje colaborativo",
        "El cuidador considera que la percepción del estudiante hacia él como actora ajena al conocimiento ha impedido establecer de rutinas de estudio",
        "El cuidador considera que su rol le permite al estudiante sentirse apoyados y con confianza",
        "El cuidador reconoce la importancia del acompañamiento académico",
      ],
      "habilidades socioemocionales": [
        "El cuidador considera que el estudiante va a sentirse seguro y respaldado al saber que tiene apoyo",
        "El cuidador considera que la interacción con  los demás cuidadores genera sensaciones positivas",
        "El cuidador espera que el acompañamiento académico desarrolle la pérdida del miedo en el estudiante",
        "El cuidador espera que el acompañamiento académico genere sensación de apoyo en el estudiante",
        "El cuidador espera que el acompañamiento académico potencie la interacción social por parte del estudiante",
      ],
      "recursos educativos": [
        "El cuidador considera necesario un informe rutinario sobre la actualidad académica del estudiante",
        "El cuidador considera que el internet permitirá involucrarse activamente en la educación del estudiante",
        "El cuidador considera que los libros le permitirán involucrarse activamente en la educación del estudiante",
        "El cuidador cree que los juegos y nuevas dinámicas les permitirían el acompañamiento académico que realiza con el estudiante",
      ],
    },
    name: "cuidador_3",
    id: 3,
    totalTags: 5,
    totalAnswers: 21,
  },
  {
    tags: [
      "capacidad académica",
      "compromiso académico",
      "conciencia de roles",
      "habilidades socioemocionales",
      "recursos educativos",
    ],
    answers: [
      "El cuidador considera el estudiante tendrá más deseo, motivación o interés de estudiar gracias al proyecto de intervención",
      "El cuidador considera necesario un informe rutinario sobre la actualidad académica del estudiante",
      "El cuidador considera que el acompañamiento académico le permite al cuidador conocer al niño y a la docente",
      "El cuidador considera que el acompañamiento académico permite que el cuidador y el estudiante aprendan",
      "El cuidador considera que el estudiante sepa más que él le ha impedido involucrarse más en su educación",
      "El cuidador considera que el internet permitirá involucrarse activamente en la educación del estudiante",
      "El cuidador considera que estar presente para que el estudiante se sienta apoyado es una acción efectiva para el aprendizaje",
      "El cuidador considera que ha olvidado cosas, y esto le ha impedido involucrarse más en la educación del estudiante",
      "El cuidador considera que la falta de costumbre en el estudiante ha impedido el establecimiento de rutinas de estudio",
      "El cuidador considera que la falta de deseo de estudiar por parte del estudiante impidió el establecimiento de rutinas de estudio",
      "El cuidador considera que la falta de internet dificulta la participación en proyectos de intervención",
      "El cuidador considera que la interacción con  los demás cuidadores genera sensaciones positivas",
      "El cuidador considera que las guías de ayuda le permitirán involucrarse activamente en la educación del estudiante",
      "El cuidador considera que prestarle atención al estudiante mientras estudia es una acción efectiva para el aprendizaje",
      "El cuidador considera que revisar las tareas que debe realizar el estudiante es una acción efectiva para el aprendizaje",
      "El cuidador considera que su rol le permite al estudiante sentirse apoyados y con confianza",
      "El cuidador cree que las actividades lúdicas e innovadoras apoyan en el aprendizaje del estudiante",
      "El cuidador espera que el acompañamiento académico desarrolle la pérdida del miedo en el estudiante",
      "El cuidador espera que el acompañamiento académico fomente un aprendizaje constante entre el estudiante y el cuidador",
      "El cuidador espera que el acompañamiento académico genere sensación de apoyo en el estudiante",
      "El cuidador espera que el acompañamiento académico potencie la interacción social por parte del estudiante",
      "El cuidador espera que el acompañamiento académico sea algo permanente en la educación del estudiante",
      "El cuidador se percibe con un rol de acompañamiento académico constante y consciente",
    ],
    tagged: {
      "conciencia de roles": [
        "El cuidador considera que el acompañamiento académico le permite al cuidador conocer al niño y a la docente",
        "El cuidador considera que el acompañamiento académico permite que el cuidador y el estudiante aprendan",
        "El cuidador considera que el acompañamiento académico permite que el cuidador y el estudiante aprendan",
        "El cuidador considera que estar presente para que el estudiante se sienta apoyado es una acción efectiva para el aprendizaje",
        "El cuidador considera que prestarle atención al estudiante mientras estudia es una acción efectiva para el aprendizaje",
        "El cuidador considera que su rol le permite al estudiante sentirse apoyados y con confianza",
        "El cuidador espera que el acompañamiento académico fomente un aprendizaje constante entre el estudiante y el cuidador",
        "El cuidador se percibe con un rol de acompañamiento académico constante y consciente",
      ],
      "capacidad académica": [
        "El cuidador considera que el estudiante sepa más que él le ha impedido involucrarse más en su educación",
        "El cuidador considera que ha olvidado cosas, y esto le ha impedido involucrarse más en la educación del estudiante",
        "El cuidador espera que el acompañamiento académico sea algo permanente en la educación del estudiante",
      ],
      "compromiso académico": [
        "El cuidador considera el estudiante tendrá más deseo, motivación o interés de estudiar gracias al proyecto de intervención",
        "El cuidador considera que la falta de costumbre en el estudiante ha impedido el establecimiento de rutinas de estudio",
        "El cuidador considera que la falta de deseo de estudiar por parte del estudiante impidió el establecimiento de rutinas de estudio",
        "El cuidador considera que revisar las tareas que debe realizar el estudiante es una acción efectiva para el aprendizaje",
      ],
      "habilidades socioemocionales": [
        "El cuidador considera que la interacción con  los demás cuidadores genera sensaciones positivas",
        "El cuidador espera que el acompañamiento académico desarrolle la pérdida del miedo en el estudiante",
        "El cuidador espera que el acompañamiento académico genere sensación de apoyo en el estudiante",
        "El cuidador espera que el acompañamiento académico potencie la interacción social por parte del estudiante",
      ],
      "recursos educativos": [
        "El cuidador considera necesario un informe rutinario sobre la actualidad académica del estudiante",
        "El cuidador considera que el internet permitirá involucrarse activamente en la educación del estudiante",
        "El cuidador considera que la falta de internet dificulta la participación en proyectos de intervención",
        "El cuidador considera que las guías de ayuda le permitirán involucrarse activamente en la educación del estudiante",
        "El cuidador cree que las actividades lúdicas e innovadoras apoyan en el aprendizaje del estudiante",
      ],
    },
    name: "cuidador_4",
    id: 4,
    totalTags: 5,
    totalAnswers: 23,
  },
  {
    tags: [
      "capacidad académica",
      "compromiso académico",
      "conciencia de roles",
      "habilidades socioemocionales",
      "recursos educativos",
    ],
    answers: [
      "El cuidador considera las rutinas de estudio son importantes para evitar la curva del olvido",
      "El cuidador considera necesario un informe rutinario sobre la actualidad académica del estudiante",
      "El cuidador considera que conocer el estilo de aprendizaje del estudiante es una acción efectiva para el aprendizaje",
      "El cuidador considera que el acompañamiento académico permite que el cuidador y el estudiante aprendan",
      "El cuidador considera que el acompañamiento académico permite saber cómo los docentes tratan al estudiante",
      "El cuidador considera que el cruce de horarios por el trabajo, la falta o el orden en el tiempo dificultó su acompañamiento",
      "El cuidador considera que el internet permitirá involucrarse activamente en la educación del estudiante",
      "El cuidador considera que la falta de costumbre en el estudiante ha impedido el establecimiento de rutinas de estudio",
      "El cuidador considera que la falta de disposición y falta de interés dificulta la participación",
      "El cuidador considera que la interacción con  los demás cuidadores genera sensaciones positivas",
      "El cuidador cree que los audios y los videos informativos fortalecerían las rutinas de estudios",
      "El cuidador cree que los juegos y nuevas dinámicas les permitirían el acompañamiento académico que realiza con el estudiante",
      "El cuidador espera que el acompañamiento académico le permita al estudiante mejorar académicamente",
      "El cuidador reconoce los resultados del acompañamiento académico en el estudiante",
      "El cuidador se percibe con un rol de facilitador de conocimiento",
    ],
    tagged: {
      "conciencia de roles": [
        "El cuidador considera las rutinas de estudio son importantes para evitar la curva del olvido",
        "El cuidador considera que el acompañamiento académico permite que el cuidador y el estudiante aprendan",
        "El cuidador considera que el acompañamiento académico permite saber cómo los docentes tratan al estudiante",
        "El cuidador reconoce los resultados del acompañamiento académico en el estudiante",
        "El cuidador se percibe con un rol de facilitador de conocimiento",
      ],
      "capacidad académica": [
        "El cuidador espera que el acompañamiento académico le permita al estudiante mejorar académicamente",
      ],
      "compromiso académico": [
        "El cuidador considera que conocer el estilo de aprendizaje del estudiante es una acción efectiva para el aprendizaje",
        "El cuidador considera que el cruce de horarios por el trabajo, la falta o el orden en el tiempo dificultó su acompañamiento",
        "El cuidador considera que la falta de costumbre en el estudiante ha impedido el establecimiento de rutinas de estudio",
        "El cuidador considera que la falta de disposición y falta de interés dificulta la participación",
      ],
      "recursos educativos": [
        "El cuidador considera necesario un informe rutinario sobre la actualidad académica del estudiante",
        "El cuidador considera que el internet permitirá involucrarse activamente en la educación del estudiante",
        "El cuidador cree que los audios y los videos informativos fortalecerían las rutinas de estudios",
        "El cuidador cree que los juegos y nuevas dinámicas les permitirían el acompañamiento académico que realiza con el estudiante",
      ],
      "habilidades socioemocionales": [
        "El cuidador considera que la interacción con  los demás cuidadores genera sensaciones positivas",
      ],
    },
    name: "cuidador_5",
    id: 5,
    totalTags: 5,
    totalAnswers: 15,
  },
  {
    tags: [
      "capacidad académica",
      "compromiso académico",
      "conciencia de roles",
      "habilidades socioemocionales",
      "recursos educativos",
    ],
    answers: [
      "El cuidador aprendió cómo se debe tratar al estudiante cuando está realizando el acompañamiento académico",
      "El cuidador considera necesario un informe rutinario sobre la actualidad académica del estudiante",
      "El cuidador considera que actividades de autosuperación para el cuidador permitiria acompañar académicamente al estudiante",
      "El cuidador considera que aumentará el acompañamiento académico hacia el estudiante",
      "El cuidador considera que conocer el estilo de aprendizaje del estudiante es una acción efectiva para el aprendizaje",
      "El cuidador considera que el acompañamiento académico permite que el estudiante aprenda más y mejor",
      "El cuidador considera que el cruce de horarios por el trabajo, la falta o el orden en el tiempo dificultó su acompañamiento",
      "El cuidador considera que la falta de deseo de estudiar por parte del estudiante impidió el establecimiento de rutinas de estudio",
      "El cuidador considera que la interacción con  los demás cuidadores genera sensaciones positivas",
      "El cuidador considera que las guías de ayuda le permitirán involucrarse activamente en la educación del estudiante",
      "El cuidador considera que las rutinas de estudio son positivas siempre y cuando se evite el agotamiento en el estudiante",
      "El cuidador considera que si le explica al estudiante este aprende más fácil",
      "El cuidador cree que los audios y los videos informativos fortalecerían las rutinas de estudios",
      "El cuidador espera que el acompañamiento académico sea algo permanente en la educación del estudiante",
      "El cuidador se percibe con un rol de facilitador de conocimiento",
    ],
    tagged: {
      "conciencia de roles": [
        "El cuidador considera que el acompañamiento académico permite que el estudiante aprenda más y mejor",
        "El cuidador considera que las rutinas de estudio son positivas siempre y cuando se evite el agotamiento en el estudiante",
        "El cuidador considera que si le explica al estudiante este aprende más fácil",
        "El cuidador se percibe con un rol de facilitador de conocimiento",
      ],
      "compromiso académico": [
        "El cuidador considera que actividades de autosuperación para el cuidador permitiria acompañar académicamente al estudiante",
        "El cuidador considera que aumentará el acompañamiento académico hacia el estudiante",
        "El cuidador considera que conocer el estilo de aprendizaje del estudiante es una acción efectiva para el aprendizaje",
        "El cuidador considera que el cruce de horarios por el trabajo, la falta o el orden en el tiempo dificultó su acompañamiento",
        "El cuidador considera que la falta de deseo de estudiar por parte del estudiante impidió el establecimiento de rutinas de estudio",
      ],
      "habilidades socioemocionales": [
        "El cuidador aprendió cómo se debe tratar al estudiante cuando está realizando el acompañamiento académico",
        "El cuidador considera que la interacción con  los demás cuidadores genera sensaciones positivas",
      ],
      "capacidad académica": [
        "El cuidador espera que el acompañamiento académico sea algo permanente en la educación del estudiante",
      ],
      "recursos educativos": [
        "El cuidador considera necesario un informe rutinario sobre la actualidad académica del estudiante",
        "El cuidador considera que las guías de ayuda le permitirán involucrarse activamente en la educación del estudiante",
        "El cuidador cree que los audios y los videos informativos fortalecerían las rutinas de estudios",
      ],
    },
    name: "cuidador_6",
    id: 6,
    totalTags: 5,
    totalAnswers: 15,
  },
  {
    tags: [
      "capacidad académica",
      "compromiso académico",
      "conciencia de roles",
      "habilidades socioemocionales",
      "recursos educativos",
    ],
    answers: [
      "El cuidador considera el estudiante tendrá más deseo, motivación o interés de estudiar gracias al proyecto de intervención",
      "El cuidador considera el estudiante tendrá proyección de estudiar en instituciones de educación superior",
      "El cuidador considera necesario un informe rutinario sobre la actualidad académica del estudiante",
      "El cuidador considera que dejar solo al estudiante lo afecta negativamente",
      "El cuidador considera que dialogar con el estudiante frente al estudio es una acción efectiva para el aprendizaje",
      "El cuidador considera que el acompañamiento académico permite que el estudiante aprenda más y mejor",
      "El cuidador considera que el cruce de horarios por el trabajo, la falta o el orden en el tiempo dificultó su acompañamiento",
      "El cuidador considera que el internet permitirá involucrarse activamente en la educación del estudiante",
      "El cuidador considera que la falta de disposición y falta de interés dificulta la participación",
      "El cuidador considera que la interacción con los demás cuidadores genera mayor por el estudiante",
      "El cuidador considera que la intervención permite que el estudiante tenga mejores calificaciones",
      "El cuidador considera que las rutinas de estudio le permiten al estudiante tener tiempo para jugar",
      "El cuidador considera que las rutinas de estudio les permiten tener claros los horarios y responsabilidades académicas a desarrollar",
      "El cuidador considera que sacar tiempo para acompañar al estudiante es una acción efectiva para el aprendizaje",
      "El cuidador considera que sentarse junto con el estudiante a estudiar es una acción efectiva para el aprendizaje",
      "El cuidador considera que su falta de conocimiento le ha impedido involucrarse más en la educación del estudiante",
      "El cuidador considera que su falta de formación académica le ha impedido involucrarse más en la educación del estudiante",
      "El cuidador considera que ver al estudiante como fuente de conocimiento es una acción efectiva para el aprendizaje",
      "El cuidador cree que el internet fortalece las rutinas de estudio",
      "El cuidador distribuye el acompañamiento académico junto con la madre de acuerdo a su capacidad académica",
      "El cuidador espera que el acompañamiento académico le permita al estudiante mejorar académicamente",
      "El cuidador espera que se genere conciencia y conocimiento por parte de los demás cuidadores sobre el acompañamiento académico",
      "El cuidador le gustaría que se incluyeran actividades para mejorar su acompañamiento académico en el estudiante",
      "El cuidador relaciona el apoyo académico con el aprendizaje del estudiante",
      "El cuidador se percibe con un rol de acompañamiento académico constante y consciente",
    ],
    tagged: {
      "conciencia de roles": [
        "El cuidador considera que dejar solo al estudiante lo afecta negativamente",
        "El cuidador considera que el acompañamiento académico permite que el estudiante aprenda más y mejor",
        "El cuidador considera que ver al estudiante como fuente de conocimiento es una acción efectiva para el aprendizaje",
        "El cuidador espera que se genere conciencia y conocimiento por parte de los demás cuidadores sobre el acompañamiento académico",
        "El cuidador relaciona el apoyo académico con el aprendizaje del estudiante",
        "El cuidador se percibe con un rol de acompañamiento académico constante y consciente",
      ],
      "capacidad académica": [
        "El cuidador considera el estudiante tendrá proyección de estudiar en instituciones de educación superior",
        "El cuidador considera que la intervención permite que el estudiante tenga mejores calificaciones",
        "El cuidador considera que su falta de conocimiento le ha impedido involucrarse más en la educación del estudiante",
        "El cuidador considera que su falta de formación académica le ha impedido involucrarse más en la educación del estudiante",
        "El cuidador espera que el acompañamiento académico le permita al estudiante mejorar académicamente",
      ],
      "compromiso académico": [
        "El cuidador considera el estudiante tendrá más deseo, motivación o interés de estudiar gracias al proyecto de intervención",
        "El cuidador considera que el cruce de horarios por el trabajo, la falta o el orden en el tiempo dificultó su acompañamiento",
        "El cuidador considera que la falta de disposición y falta de interés dificulta la participación",
        "El cuidador considera que las rutinas de estudio le permiten al estudiante tener tiempo para jugar",
        "El cuidador considera que las rutinas de estudio les permiten tener claros los horarios y responsabilidades académicas a desarrollar",
        "El cuidador considera que sacar tiempo para acompañar al estudiante es una acción efectiva para el aprendizaje",
        "El cuidador considera que sentarse junto con el estudiante a estudiar es una acción efectiva para el aprendizaje",
        "El cuidador distribuye el acompañamiento académico junto con la madre de acuerdo a su capacidad académica",
      ],
      "habilidades socioemocionales": [
        "El cuidador considera que dialogar con el estudiante frente al estudio es una acción efectiva para el aprendizaje",
        "El cuidador considera que la interacción con los demás cuidadores genera mayor por el estudiante",
      ],
      "recursos educativos": [
        "El cuidador considera necesario un informe rutinario sobre la actualidad académica del estudiante",
        "El cuidador considera que el internet permitirá involucrarse activamente en la educación del estudiante",
        "El cuidador cree que el internet fortalece las rutinas de estudio",
        "El cuidador le gustaría que se incluyeran actividades para mejorar su acompañamiento académico en el estudiante",
      ],
    },
    name: "cuidador_7",
    id: 7,
    totalTags: 5,
    totalAnswers: 25,
  },
  {
    tags: [
      "capacidad académica",
      "compromiso académico",
      "conciencia de roles",
      "habilidades socioemocionales",
      "recursos educativos",
    ],
    answers: [
      "El docente-investigador considera como exitosa la participación de los cuidadores y estudiantes",
      "El docente-investigador considera como exitoso los cambios comportamentales de estudiantes y cuidadores",
      "El docente-investigador considera como lección más importante que aprende quien quiere aprender",
      "El docente-investigador considera exitosa el cambio de comunicación hacia el docente",
      "El docente-investigador considera exitosa la interacción entre cuidadores y estudiantes",
      "El docente-investigador considera exitoso el desarrollo del interes en los cuidadores por actividades académicas",
      "El docente-investigador considera que desarrollar actividades de alfabetización digital puede ser importante para el futuro",
      "El docente-investigador considera que el poco conocimiento del uso de la tecnología fué un desafió para la intervención",
      "El docente-investigador considera que la nula participación de los cuidadores más desinteresados fué un desafió para la intervención",
      "El docente-investigador considera que las actividades fisicas fueron efectivas",
      "El docente-investigador considera que las actividades relacionadas con redes sociales fueron efectivas",
      "El docente-investigador menciona que las reacciones de los cuidadores frente al proyecto de intervención eran de excusas",
      "El docente-investigador menciona que las reacciones de los cuidadores frente al proyecto de intervención eran de reflexión",
      "El docente-investigador menciona que las reacciones de los cuidadores frente al proyecto de intervención eran de sorpresa",
      "El docente-investigador permitió que las actividades digitales podian ser realizadas a mano",
      "El docente-investigador reconoce el cambio de actitud por parte de los cuidadores frente a la comunicación con el docente",
      "El docente-investigador reconoce que los cuidadores empezaron a hacer uso de mensajes digitales y fisicos para comunicarse con el docente",
      "El docente-investigador reconoce que mejoró la comunicación entre docente y cuidadores",
      "El docente-investigador reconoce que se generó un interes en los cuidadores frente al rendimiento académico de los estudiantes",
      "El docente-investigador reconoce que se identifiaron resistencias frente a la posición de aprendizajes nuevos en los cuidadores debido a su edad",
      "El docente-investigador reconoce que se identificaron resistencias en los cuidadores para tomar el rol de maestro hacia los estudiantes",
      "El docente-investigador reconoce que se identificó una relación entre el manejo tecnologico y el contexto socioeconomico y cultural de los cuidadores",
      "El docente-investigador sugiere el desarrollo de más actividades presenciales para proyectos similares",
      "Los cuidadores se percibian viejos para aprender cosas nuevas",
    ],
    tagged: {
      "compromiso académico": [
        "El docente-investigador considera como exitosa la participación de los cuidadores y estudiantes",
        "El docente-investigador considera como exitoso los cambios comportamentales de estudiantes y cuidadores",
        "El docente-investigador considera como lección más importante que aprende quien quiere aprender",
        "El docente-investigador considera exitosa el cambio de comunicación hacia el docente",
        "El docente-investigador considera exitoso el desarrollo del interes en los cuidadores por actividades académicas",
        "El docente-investigador considera que la nula participación de los cuidadores más desinteresados fué un desafió para la intervención",
        "El docente-investigador menciona que las reacciones de los cuidadores frente al proyecto de intervención eran de excusas",
        "El docente-investigador menciona que las reacciones de los cuidadores frente al proyecto de intervención eran de excusas",
        "El docente-investigador menciona que las reacciones de los cuidadores frente al proyecto de intervención eran de reflexión",
        "El docente-investigador menciona que las reacciones de los cuidadores frente al proyecto de intervención eran de reflexión",
        "El docente-investigador menciona que las reacciones de los cuidadores frente al proyecto de intervención eran de sorpresa",
        "El docente-investigador menciona que las reacciones de los cuidadores frente al proyecto de intervención eran de sorpresa",
        "El docente-investigador reconoce que los cuidadores empezaron a hacer uso de mensajes digitales y fisicos para comunicarse con el docente",
        "El docente-investigador reconoce que se generó un interes en los cuidadores frente al rendimiento académico de los estudiantes",
        "El docente-investigador reconoce que se identifiaron resistencias frente a la posición de aprendizajes nuevos en los cuidadores debido a su edad",
        "El docente-investigador reconoce que se identificaron resistencias en los cuidadores para tomar el rol de maestro hacia los estudiantes",
      ],
      "habilidades socioemocionales": [
        "El docente-investigador considera exitosa la interacción entre cuidadores y estudiantes",
        "El docente-investigador reconoce el cambio de actitud por parte de los cuidadores frente a la comunicación con el docente",
        "El docente-investigador reconoce que mejoró la comunicación entre docente y cuidadores",
      ],
      "capacidad académica": [
        "El docente-investigador considera que el poco conocimiento del uso de la tecnología fué un desafió para la intervención",
      ],
      "recursos educativos": [
        "El docente-investigador considera que desarrollar actividades de alfabetización digital puede ser importante para el futuro",
        "El docente-investigador considera que las actividades fisicas fueron efectivas",
        "El docente-investigador considera que las actividades relacionadas con redes sociales fueron efectivas",
        "El docente-investigador permitió que las actividades digitales podian ser realizadas a mano",
        "El docente-investigador reconoce que se identificó una relación entre el manejo tecnologico y el contexto socioeconomico y cultural de los cuidadores",
        "El docente-investigador sugiere el desarrollo de más actividades presenciales para proyectos similares",
      ],
      "conciencia de roles": [
        "Los cuidadores se percibian viejos para aprender cosas nuevas",
      ],
    },
    name: "docente",
    id: 8,
    totalTags: 5,
    totalAnswers: 24,
  },
];
